# Generated by Django 6.0.2 on 2026-02-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Short unique code for this visa type, e.g. TOURIST_30.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text="Application fee in the system's base currency.", max_digits=10)),
                ('max_stay_days', models.PositiveIntegerField(help_text='Maximum number of days the holder may stay per visit.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Visa Type',
                'verbose_name_plural': 'Visa Types',
                'db_table': 'visas_visatype',
                'indexes': [models.Index(fields=['is_active', 'name'], name='idx_visatype_active_name')],
            },
        ),
    ]
