# Generated by Django 6.0.2 on 2026-02-22 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('PHOTO', 'Passport-size Photo'), ('BANK_STATEMENT', 'Bank Statement'), ('INVITATION_LETTER', 'Invitation Letter'), ('TRAVEL_ITINERARY', 'Travel Itinerary'), ('ACCOMMODATION_PROOF', 'Accommodation Proof'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('file_path', models.CharField(help_text='Relative path or object-storage key for the uploaded file.', max_length=512)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='applications.visaapplication')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'db_table': 'documents_applicationdocument',
                'indexes': [models.Index(fields=['application', 'verified'], name='idx_doc_app_verified'), models.Index(fields=['application', 'document_type'], name='idx_doc_app_type')],
                'constraints': [models.UniqueConstraint(fields=('application', 'document_type'), name='uq_doc_application_type')],
            },
        ),
    ]
