# Generated by Django 6.0.2 on 2026-02-22 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_INFO', 'Pending Additional Information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=20)),
                ('nationality', models.CharField(help_text="ISO 3166-1 alpha-2 country code, e.g. 'NG'.", max_length=2)),
                ('purpose_of_travel', models.CharField(max_length=255)),
                ('intended_entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('soft_deleted_at', models.DateTimeField(blank=True, help_text='Non-null means this record is logically deleted.', null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='visas.visatype')),
            ],
            options={
                'verbose_name': 'Visa Application',
                'verbose_name_plural': 'Visa Applications',
                'db_table': 'applications_visaapplication',
                'indexes': [models.Index(fields=['applicant', 'created_at'], name='idx_app_applicant_created'), models.Index(fields=['status', 'soft_deleted_at'], name='idx_app_status_softdel')],
            },
        ),
    ]
