# Generated by Django 6.0.2 on 2026-02-22 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUEST_INFO', 'Request More Information')], db_index=True, max_length=15)),
                ('reason', models.TextField(help_text="Officer's written justification for the decision.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='applications.visaapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Decision',
                'verbose_name_plural': 'Review Decisions',
                'db_table': 'reviews_reviewdecision',
                'indexes': [models.Index(fields=['application', 'created_at'], name='idx_review_app_created'), models.Index(fields=['reviewer', 'created_at'], name='idx_review_reviewer_created')],
            },
        ),
    ]
